// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

/**
 * Helper: génère les items Diátaxis pour un service.
 * Le dossier how-to/ utilise autogenerated + generated-index
 * pour fonctionner même quand il est vide.
 * La page api-reference n'y figure plus : elle décrit les manifestes
 * apps.cozystack.io (méthode kubeconfig legacy) et reste en `unlisted`
 * jusqu'à la documentation de l'API Hikube.
 */
function diatasisItems(basePath, extraItems) {
  const key = `how-to-${basePath.replace(/\//g, "-")}`;
  return [
    `${basePath}/overview`,
    `${basePath}/concepts`,
    `${basePath}/quick-start`,
    {
      type: "category",
      label: "Guides pratiques",
      key,
      link: { type: "generated-index", title: "Guides pratiques" },
      items: [{ type: "autogenerated", dirName: `${basePath}/how-to` }],
    },
    ...(extraItems || []),
    `${basePath}/faq`,
    `${basePath}/troubleshooting`,
  ];
}

const sidebars = {
  docsSidebar: [
    {
      type: "doc",
      id: "get-started",
    },
    {
      type: "category",
      label: "Démarrer",
      items: [
        "getting-started/introduction",
        "getting-started/concepts",
        "getting-started/quick-start",
      ],
    },
    {
      type: "category",
      label: "Services",
      items: [
        {
          type: "category",
          label: "Storage",
          link: { type: "doc", id: "services/storage/index" },
          items: [
            {
              type: "category",
              label: "Disques",
              items: diatasisItems("services/storage/disks"),
            },
            {
              type: "category",
              label: "Buckets",
              items: diatasisItems("services/storage/buckets"),
            },
          ],
        },
        {
          type: "category",
          label: "Databases",
          link: { type: "doc", id: "services/databases/index" },
          items: [
            {
              type: "category",
              label: "PostgreSQL",
              items: diatasisItems("services/databases/postgresql"),
            },
            {
              type: "category",
              label: "MariaDB",
              items: diatasisItems("services/databases/mariadb"),
            },
            {
              type: "category",
              label: "MongoDB",
              items: diatasisItems("services/databases/mongodb"),
            },
            {
              type: "category",
              label: "Redis",
              items: diatasisItems("services/databases/redis"),
            },
            {
              type: "category",
              label: "ClickHouse",
              items: diatasisItems("services/databases/clickhouse"),
            },
          ],
        },
        {
          type: "category",
          label: "Ressources de calcul",
          link: { type: "doc", id: "services/compute/index" },
          items: diatasisItems("services/compute"),
        },
        {
          type: "category",
          label: "GPU",
          link: { type: "doc", id: "services/gpu/index" },
          items: diatasisItems("services/gpu"),
        },
        {
          type: "category",
          label: "Kubernetes",
          link: { type: "doc", id: "services/kubernetes/index" },
          items: diatasisItems("services/kubernetes", [
            {
              type: "category",
              label: "Plugins",
              items: [
                "services/kubernetes/plugins/cilium",
                "services/kubernetes/plugins/coredns",
                "services/kubernetes/plugins/gateway-api",
                "services/kubernetes/plugins/verticalpodautoscaler",
                "services/kubernetes/plugins/ingress-nginx",
                "services/kubernetes/plugins/ouroboros",
                "services/kubernetes/plugins/cert-manager",
                "services/kubernetes/plugins/gpu-operator",
                "services/kubernetes/plugins/hami",
                "services/kubernetes/plugins/fluxcd",
                "services/kubernetes/plugins/velero",
                "services/kubernetes/plugins/monitoring-agents",
              ],
            },
          ]),
        },
        {
          type: "category",
          label: "Réseau",
          link: { type: "doc", id: "services/networking/index" },
          items: diatasisItems("services/networking"),
        },
        {
          type: "category",
          label: "Messaging",
          link: { type: "doc", id: "services/messaging/index" },
          items: [
            {
              type: "category",
              label: "RabbitMQ",
              items: diatasisItems("services/messaging/rabbitmq"),
            },
            {
              type: "category",
              label: "Kafka",
              items: diatasisItems("services/messaging/kafka"),
            },
            {
              type: "category",
              label: "NATS",
              items: diatasisItems("services/messaging/nats"),
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Ressources",
      items: [
        "resources/troubleshooting",
        "resources/faq",
        "resources/glossary",
      ],
    },
    {
      type: "category",
      label: "Outils",
      items: ["tools/terraform"],
    },
  ],
};

export default sidebars;
