import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/reference/hikube-api",
    },
    {
      type: "category",
      label: "Billing",
      items: [
        {
          type: "doc",
          id: "api/reference/billing-service-list-instance-prices",
          label: "List instance (VM) prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-database-prices",
          label: "List database prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-kubernetes-prices",
          label: "List Kubernetes (managed control plane) prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-licenses-prices",
          label: "List OS licence prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-gpu-prices",
          label: "List GPU prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-network-prices",
          label: "List network prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-block-storage-prices",
          label: "List block storage prices (per GiB)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/billing-service-list-object-storage-prices",
          label: "List object storage prices (per GiB)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Object Storage",
      items: [
        {
          type: "doc",
          id: "api/reference/bucket-service-list-buckets",
          label: "List Buckets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-create-bucket",
          label: "Create Bucket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-get-bucket",
          label: "Get Bucket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-delete-bucket",
          label: "Delete Bucket",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-list-users",
          label: "List Bucket Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-create-user",
          label: "Create Bucket User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-get-user",
          label: "Get Bucket User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-delete-user",
          label: "Delete Bucket User",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-update-user",
          label: "Update Bucket User",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/bucket-service-rotate-user-credentials",
          label: "Rotate Bucket User Credentials",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Disk Storage",
      items: [
        {
          type: "doc",
          id: "api/reference/disk-service-list-disks",
          label: "List Disks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/disk-service-create-disk",
          label: "Create Disk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/disk-service-get-disk",
          label: "Get Disk",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/disk-service-delete-disk",
          label: "Delete Disk",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/disk-service-update-disk",
          label: "Update Disk",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "GPU",
      items: [
        {
          type: "doc",
          id: "api/reference/gpu-service-list-gpus",
          label: "List GPU types and availability",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Instance",
      items: [
        {
          type: "doc",
          id: "api/reference/instance-service-list-instances",
          label: "List Instances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-create-instance",
          label: "Create Instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-get-instance",
          label: "Get Instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-delete-instance",
          label: "Delete Instance",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-update-instance",
          label: "Update Instance",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-start-instance",
          label: "Start Instance",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-stop-instance",
          label: "Stop Instance",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-restart-instance",
          label: "Restart Instance",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-reload-instance-user-data",
          label: "Reload UserData script",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-list-cloud-images",
          label: "List Available Cloud Images",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/instance-service-list-instance-types",
          label: "List Available Instance Types",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Kubernetes",
      items: [
        {
          type: "doc",
          id: "api/reference/kubernetes-service-list-kubernetes-clusters",
          label: "List clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-create-kubernetes-cluster",
          label: "Create cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-get-kubernetes-cluster",
          label: "Get cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-delete-kubernetes-cluster",
          label: "Delete cluster",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-update-kubernetes-cluster",
          label: "Update cluster",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-get-kubernetes-cluster-kubeconfig",
          label: "Get kubeconfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-list-kubernetes-versions",
          label: "List available Kubernetes versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/kubernetes-service-list-kubernetes-presets",
          label: "List resource presets allowed for the Kubernetes control plane",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "MariaDB",
      items: [
        {
          type: "doc",
          id: "api/reference/maria-db-service-list-maria-db-clusters",
          label: "List clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-create-maria-db-cluster",
          label: "Create cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-get-maria-db-cluster",
          label: "Get cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-delete-maria-db-cluster",
          label: "Delete cluster",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-update-maria-db-cluster",
          label: "Update cluster",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-list-databases",
          label: "List databases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-create-database",
          label: "Create database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-get-database",
          label: "Get database",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-delete-database",
          label: "Delete database",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-list-users",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-create-user",
          label: "Create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-get-user",
          label: "Get user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-delete-user",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-update-user",
          label: "Update user",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-rotate-user-password",
          label: "Rotate user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/maria-db-service-list-maria-db-presets",
          label: "List resource presets allowed for mariadb",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "MongoDB",
      items: [
        {
          type: "doc",
          id: "api/reference/mongo-db-service-list-mongo-db-clusters",
          label: "List clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-create-mongo-db-cluster",
          label: "Create cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-get-mongo-db-cluster",
          label: "Get cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-delete-mongo-db-cluster",
          label: "Delete cluster",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-update-mongo-db-cluster",
          label: "Update cluster",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-list-databases",
          label: "List databases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-create-database",
          label: "Create database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-get-database",
          label: "Get database",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-delete-database",
          label: "Delete database",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-list-users",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-create-user",
          label: "Create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-get-user",
          label: "Get user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-delete-user",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-update-user",
          label: "Update user",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-rotate-user-password",
          label: "Rotate user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/mongo-db-service-list-mongo-db-presets",
          label: "List resource presets allowed for mongodb",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Network",
      items: [
        {
          type: "doc",
          id: "api/reference/network-service-list-vp-cs",
          label: "List VPCs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/network-service-create-vpc",
          label: "Create VPC",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/network-service-get-vpc",
          label: "Get VPC",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/network-service-delete-vpc",
          label: "Delete VPC",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/network-service-list-subnets",
          label: "List Subnets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/network-service-create-subnet",
          label: "Create Subnet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/network-service-get-subnet",
          label: "Get Subnet",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/network-service-delete-subnet",
          label: "Delete Subnet",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Postgres",
      items: [
        {
          type: "doc",
          id: "api/reference/postgres-service-list-postgres-clusters",
          label: "List clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-create-postgres-cluster",
          label: "Create cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-get-postgres-cluster",
          label: "Get cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-delete-postgres-cluster",
          label: "Delete cluster",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-update-postgres-cluster",
          label: "Update cluster",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-list-databases",
          label: "List databases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-create-database",
          label: "Create database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-get-database",
          label: "Get database",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-delete-database",
          label: "Delete database",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-update-database",
          label: "Update database",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-list-extensions",
          label: "List available PostgreSQL extensions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-list-postgres-presets",
          label: "List resource presets allowed for postgres",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-list-users",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-create-user",
          label: "Create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-get-user",
          label: "Get user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-delete-user",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-update-user",
          label: "Update user",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/postgres-service-rotate-user-password",
          label: "Rotate user password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "RabbitMQ",
      items: [
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-list-rabbit-mq-clusters",
          label: "List clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-create-rabbit-mq-cluster",
          label: "Create cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-get-rabbit-mq-cluster",
          label: "Get cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-delete-rabbit-mq-cluster",
          label: "Delete cluster",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-update-rabbit-mq-cluster",
          label: "Update cluster",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-list-users",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-create-user",
          label: "Create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-get-user",
          label: "Get user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-delete-user",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-update-user",
          label: "Update user",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-rotate-user-password",
          label: "Rotate user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-list-vhosts",
          label: "List vhosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-create-vhost",
          label: "Create vhost",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-get-vhost",
          label: "Get vhost",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-delete-vhost",
          label: "Delete vhost",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/rabbit-mq-service-list-rabbit-mq-presets",
          label: "List resource presets allowed for rabbitmq",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Redis",
      items: [
        {
          type: "doc",
          id: "api/reference/redis-service-list-redis-clusters",
          label: "List clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/redis-service-create-redis-cluster",
          label: "Create cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/redis-service-get-redis-cluster",
          label: "Get cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/redis-service-delete-redis-cluster",
          label: "Delete cluster",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reference/redis-service-update-redis-cluster",
          label: "Update cluster",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reference/redis-service-rotate-password",
          label: "Rotate cluster password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reference/redis-service-list-redis-presets",
          label: "List resource presets allowed for redis",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
