name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy:
    name: Deploy Preview
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages (Preview)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
